Numpy and Pandas

Numpy Operations

In [2]:
import numpy as np

In [3]:
'''creating an array '''

a = np.array([1,2,3,4,5])
print("Array:", a)

Array: [1 2 3 4 5]


In [6]:
'''Reshaping array'''
b = np.array([1,2,3,4,5,6])
print("Reshaped Array:\n", b.reshape(2,3))

Reshaped Array:
 [[1 2 3]
 [4 5 6]]


In [23]:
'''Mathematical Operations'''

x = np.array([1,2,3,4])
y = np.array([3,4,5,6])

print("Addition:", x+y )
print("Mean:", np.mean(x))
print("Standard Devation:", np.std(x))

Addition: [ 4  6  8 10]
Mean: 2.5
Standard Devation: 1.118033988749895


In [8]:
'''Indexing  &  Slicing'''

arr = np.array([100,200,300,400,500])
print("Third element:", arr[2])
print("Slice:", arr[1:4])

Third element: 300
Slice: [200 300 400]


In [14]:
'''Random Number Generator'''

print("Random numbers:\n", 
      np.random.randint(3,10,5))

Random numbers:
 [4 3 7 8 6]


In [16]:
'''Create a 2D static array'''

arr = np.array([[1,2,3],
               [4,5,6]])
print("2D array:\n", arr)

2D array:
 [[1 2 3]
 [4 5 6]]


In [17]:
print("Row-wise Std dev:",
      np.std(arr, axis=1))

Row-wise Std dev: [0.81649658 0.81649658]


In [18]:
print("Column-wise Std dev:", 
      np.std(arr, axis=1))

Column-wise Std dev: [0.81649658 0.81649658]


In [19]:
print("Overall Std dev:",
      np.std(arr))

Overall Std dev: 1.707825127659933


In [20]:
'''flatten array'''

flat = arr.flatten()
print("Flatten Array:", flat)

Flatten Array: [1 2 3 4 5 6]


Pandas Operation

In [25]:
import pandas as pd

In [39]:
'''Creating DataFrame'''

a = {
    "Name": ["Anand", "Rahul", "Sneha"],
    "Marks": [85,90,95]
}
df = pd.DataFrame(a)
print(df)

    Name  Marks
0  Anand     85
1  Rahul     90
2  Sneha     95


In [43]:
'''Viewing Data'''
print(df.head())
print(df.tail())

    Name  Marks
0  Anand     85
1  Rahul     90
2  Sneha     95
    Name  Marks
0  Anand     85
1  Rahul     90
2  Sneha     95


In [46]:
'''Selecting Columns'''

print(df["Marks"])
print(df["Name"])


0    85
1    90
2    95
Name: Marks, dtype: int64
0    Anand
1    Rahul
2    Sneha
Name: Name, dtype: str


In [47]:
'''Handling Missing Values'''
df.isnull()

Name  Marks
0  False  False
1  False  False
2  False  False

In [48]:
'''Grouping Data'''

print(df.groupby("Name")["Marks"].mean())

Name
Anand    85.0
Rahul    90.0
Sneha    95.0
Name: Marks, dtype: float64


In [52]:

a = {
    "Name": ["Anand", "Rahul", "Sneha"],
    "Marks": [85,90,95],
    "Age": [21,22,30]
}
df = pd.DataFrame(a)
print("First Data Frame:\n", df)

First Data Frame:
     Name  Marks  Age
0  Anand     85   21
1  Rahul     90   22
2  Sneha     95   30


In [53]:

a = {
    "Name": ["Anand", "Sneha"],
    "Marks": [85,90],
    "Age": [21,22]
}
df = pd.DataFrame(a)
print("Second Data Frame:\n", df)

Second Data Frame:
     Name  Marks  Age
0  Anand     85   21
1  Sneha     90   22


In [59]:
'''accessing the single row'''
print(df.loc[0])

Name     Anand
Marks       85
Age         21
Name: 0, dtype: object


In [57]:
'''access column'''
print(df["Name"])

0    Anand
1    Sneha
Name: Name, dtype: str


In [62]:
print(df.iloc[0])
print(df.iloc[1,1])

Name     Anand
Marks       85
Age         21
Name: 0, dtype: object
90


In [64]:
df_dropped=df.drop(0)
print("After Droping Row:\n",
      df_dropped)

After Droping Row:
     Name  Marks  Age
1  Sneha     90   22
